# Generated by Django 5.0.1 on 2024-01-10 22:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='action',
            field=models.CharField(default='Пить воду', max_length=70, verbose_name='Привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='enjoyable_habit',
            field=models.CharField(blank=True, choices=[('THYS', 'благодарить себя за достижения'), ('CRTM', 'позволять себе время на творчество'), ('WKOU', 'гулять на свежем воздухе'), ('TWHF', 'проводить время с близкими и друзьями'), ('RDBK', 'читать любимую книгу перед сном'), ('WAFM', 'смотреть любимый фильм вечером'), ('ATET', 'посетить полезное мероприятие')], null=True, verbose_name='Приятная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('ONE', 'ежедневно'), ('WEEK', 'один раз в неделю')], default='ONE', verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='habit',
            name='healthy_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Полезная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Признак публичности'),
        ),
        migrations.AddField(
            model_name='habit',
            name='lead_time',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение'),
        ),
        migrations.AddField(
            model_name='habit',
            name='place',
            field=models.CharField(choices=[('HOME', 'дома'), ('KTCH', 'на кухне'), ('PRKG', 'на парковке'), ('POOL', 'в бассейне'), ('LBR', 'в библиотеке'), ('CAFE', 'в кофейне'), ('GADN', 'в саду'), ('PARK', 'в парке'), ('OFCE', 'на работе'), ('WALK', 'на прогулке'), ('FITR', 'в тренировочном зале'), ('SHOP', 'в магазине')], default='HOME', max_length=4, verbose_name='Место выполнения привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение за выполнение'),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='creator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки'),
        ),
    ]
