# Generated by Django 4.2.9 on 2024-01-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_lead_time_alter_habit_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='on_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала выполнения привычки'),
        ),
    ]
