# Generated by Django 4.2.9 on 2024-01-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_on_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='start_time',
        ),
    ]
