# Generated by Django 4.2.9 on 2024-01-12 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_habit_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='enjoyable_habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='is_habit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Использовать приятную привычку'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='healthy_habit',
            field=models.ForeignKey(blank=True, help_text='Вы можете использовать одно из двух: указать полезную привычку или вознаграждение.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='Вы можете использовать одно из двух: указать полезную привычку или вознаграждение.', max_length=150, null=True, verbose_name='Вознаграждение за выполнение'),
        ),
    ]
