# Generated by Django 4.2.9 on 2024-01-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habit_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(choices=[('HOME', 'дома'), ('KCHEN', 'на кухне'), ('PING', 'на парковке'), ('POOL', 'в бассейне'), ('LARY', 'в библиотеке'), ('CHOP', 'в кофейне'), ('GDEN', 'в саду'), ('PARK', 'в парке'), ('OICE', 'на работе'), ('WALK', 'на прогулке'), ('FOOM', 'в тренировочном зале'), ('SHOP', 'в магазине')], default='HOME', verbose_name='Место выполнения привычки'),
        ),
    ]
